services:
  mysql-server:
    image: mysql:8.2
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: mysqld --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql-server/data:/var/lib/mysql
      - ./docker/mysql-server/init:/docker-entrypoint-initdb.d
      - ./docker/mysql-server/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    networks:
      - cdp-network

  hdfs-namenode:
    image: apache/hadoop:3.3.6
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - ./docker/hadoop/dfs/namenode:/hadoop/dfs/namenode
      - ./docker/hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker/hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./docker/hadoop/script/start-namenode.sh:/start-namenode.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hdfs-namenode:9870/"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["/bin/bash", "-c", "/start-namenode.sh"]
    restart: always
    networks:
      - cdp-network

  hdfs-datanode:
    image: apache/hadoop:3.3.6
    container_name: hdfs-datanode
    hostname: hdfs-datanode
    ports:
      - "9864:9864"
    depends_on:
      hdfs-namenode:
        condition: service_healthy
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - ./docker/hadoop/dfs/datanode:/hadoop/dfs/datanode
      - ./docker/hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker/hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./docker/hadoop/script/start-datanode.sh:/start-datanode.sh
    command: ["/bin/bash", "-c", "/start-datanode.sh"]
    restart: always
    networks:
      - cdp-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdp-for-service
    ports:
      - "8080:8080"
    working_dir: /app
    command: sh bin/run.sh
    depends_on:
      mysql-server:
        condition: service_started
      hdfs-namenode:
        condition: service_healthy
    networks:
      - cdp-network

networks:
  cdp-network:
    driver: bridge

    
