services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdp-for-service
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: sh bin/run.sh
