services:
  mysql-server:
    image: mysql:8.2
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: mysqld --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql-server/data:/var/lib/mysql
      - ./docker/mysql-server/init:/docker-entrypoint-initdb.d
      - ./docker/mysql-server/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - cdp-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdp-for-service
    ports:
      - "8080:8080"
    working_dir: /app
    command: sh bin/run.sh
    depends_on:
      mysql-server:
        condition: service_healthy
    networks:
      - cdp-network

networks:
  cdp-network:
    driver: bridge

    
