services:
  mysql-server:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-server
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: mysqld --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql-server/data:/var/lib/mysql
      - ./docker/mysql-server/init:/docker-entrypoint-initdb.d
      - ./docker/mysql-server/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    networks:
      - cdp-network

  hdfs-standalone:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-standalone
    hostname: hdfs-standalone
    ports:
      - "9870:9870"
      - "9000:9000"
      - "9864:9864"
    env_file:
      - .env
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - ./docker/hadoop/dfs/namenode:/hadoop/dfs/namenode
      - ./docker/hadoop/dfs/datanode:/hadoop/dfs/datanode
      - ./docker/hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker/hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./docker/hadoop/script/start-standalone.sh:/start-standalone.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hdfs-standalone:9870/"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["/bin/bash", "-c", "/start-standalone.sh"]
    restart: always
    networks:
      - cdp-network

  tidb-server:
    image: pingcap/tidb:${TIDB_VERSION}
    container_name: tidb-server
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: 
      - --config=/tidb.toml
    volumes:
      - ./docker/tidb/tidb.toml:/tidb.toml:ro
    restart: always
    networks:
      - cdp-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdp-for-service
    ports:
      - "8080:8080"
    working_dir: /app
    command: sh bin/run.sh
    depends_on:
      hdfs-standalone:
        condition: service_healthy
      tidb-server:
        condition: service_started
      mysql-server:
        condition: service_started
    networks:
      - cdp-network

networks:
  cdp-network:
    driver: bridge

    
