name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Google Cloud VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Navigate to project directory
          cd ./projects/reporting-tool
          
          # Fetch and pull latest code
          echo "Fetching latest code..."
          git fetch origin main
          
          echo "Pulling latest code..."
          git pull origin main
          
          # Stop old containers
          echo "Stopping old containers..."
          docker compose -f docker-compose.prod.yml down
          
          # Wait for containers to stop completely
          echo "Waiting for containers to stop..."
          sleep 10
          
          # Clean old images
          echo "Cleaning old images..."
          make clean-images
          
          # Start new containers
          echo "Starting new containers..."
          docker compose -f docker-compose.prod.yml up -d
          
          # Wait for containers to start
          echo "Waiting for containers to start..."
          sleep 15
          
          # Check container status
          echo "Checking container status..."
          docker compose -f docker-compose.prod.yml ps
          
          echo "Deployment completed!" 