name: Check Deployment Status

on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Check deployment status
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          
          echo "=== Deployment Status Check ==="
          echo "Timestamp: $(date)"
          echo ""
          
          echo "=== Container Status ==="
          docker compose -f docker-compose.prod.yml ps
          echo ""
          
          echo "=== Service Health Checks ==="
          # Check Eureka Discovery Server
          echo "Eureka Discovery Server:"
          curl -f http://localhost:8761/actuator/health || echo "Eureka Discovery Server is not healthy"
          echo ""
          
          # Check API Gateway
          echo "API Gateway:"
          curl -f http://localhost:8765/actuator/health || echo "API Gateway is not healthy"
          echo ""
          
          # Check Frontend
          echo "Frontend:"
          curl -f http://localhost:80 || echo "Frontend is not accessible"
          echo ""
          
          echo "=== Recent Logs ==="
          docker compose -f docker-compose.prod.yml logs --tail=20
          
    - name: Send notification on success
      if: success()
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Check the deployment status in the logs above."
        
    - name: Send notification on failure
      if: failure()
      run: |
        echo "❌ Deployment status check failed!"
        echo "Please check the server logs for more details." 