name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Google Cloud VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Navigate to project directory
          cd ${{ secrets.PROJECT_PATH }}
          
          # Make deploy script executable
          chmod +x scripts/deploy.sh
          
          # Run deployment script
          echo "Starting deployment process..."
          ./scripts/deploy.sh deploy
          
          # Check deployment status
          echo "Checking deployment status..."
          ./scripts/deploy.sh status
          
          echo "Deployment process completed!" 