name: Test Connection

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Make test script executable
      run: chmod +x scripts/test-connection.sh
      
    - name: Test SSH connection
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PORT: ${{ secrets.PORT }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        echo "Testing SSH connection to production server..."
        if [ -z "$HOST" ] || [ -z "$USERNAME" ] || [ -z "$SSH_KEY" ] || [ -z "$PROJECT_PATH" ]; then
          echo "❌ Missing required secrets. Please configure all required secrets:"
          echo "   - HOST"
          echo "   - USERNAME" 
          echo "   - SSH_PRIVATE_KEY"
          echo "   - PROJECT_PATH"
          exit 1
        fi
        ./scripts/test-connection.sh
        
    - name: Connection test summary
      if: always()
      run: |
        echo "Connection test completed"
        echo "Check the logs above for detailed results" 